backend:
  name: github
  repo: PhilWelsh/artblog

publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: philwelsh
    api_key: 514164997833992
    default_transformations:
      [[{ quality: "auto" }, { fetch_format: "auto" }], [{ f_auto, q_auto }]]

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/dailies"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "slug", label: "slug", widget: string }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: datetime }
      - { name: "image", label: "Cover Image", widget: image }
      - { name: "intro", label: "Intro", widget: "string" }
      - { name: "body", label: "Body", widget: markdown }
